title: Piotr Bakker &middot; Early-stage Product Design
description: I help technology companies make software people love to use.
author: Piotr Bakker
location: "San Francisco, CA"
keywords: Chatbot Design, Conversational Interface Design, Curriculum Vitae, CV, Design, Designer, Design System, Design Systems, Freelance Designer, Graphical Interface Design, Interface, Interface Design, Mobile, Mobile App Design, Portfolio, Product, Product Design, Product Manager, Responsive Web Design, Resume, User Experience, User Experience Design, User Interface, User Interface Design, UI, UX, Visual Design, Web Design, Work Experience
baseurl: ""
url: "https://piotrbakker.com"
github:
  username: piotrbakker
  repository: piotrbakker.com

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - _site/
